services:
  - type: web
    name: yatirim-asistani-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir bot bot:app
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TAVILY_API_KEY
        sync: false
